sudo: required

env:
  - ARCH_TRAVIS_VERBOSE=1

arch:
  packages:
    - python
    - python3
    - mpv
  script:
    - pip install coveralls

script:
  coverage run --source=fuocore setup.py test
after_success:
  coveralls
