sudo: required

env:
  - ARCH_TRAVIS_VERBOSE=1

arch:
  packages:
    - python3
    - mpv

install:
  - pip install coveralls
  - python setup.py install
  - python --version

script:
  coverage run --source=fuocore setup.py test

after_success:
  coveralls
