sudo: required

env:
  - ARCH_TRAVIS_VERBOSE=1

arch:
  packages:
    - python3
    - mpv
  script:
    - python --version
    - pip install coveralls
    - coverage run --source=fuocore setup.py test

script:
  - curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash

after_success:
  coveralls
