sudo: required
language: python
python:
  - "3.4"
  - "3.5"

arch:
  packages:
    - mpv
    - youtube-dl
    - mpv-libs
    - mpv-devel

install:
  - pip install coveralls
  - python setup.py install
script:
  coverage run --source=fuocore setup.py test
after_success:
  coveralls
